travis:
  secure:
    BINSTAR_TOKEN: hjgEjqQMMuIl7cpw9waAiSRTACtjX6JipcaBR0kluLMpr3GJkOLugBbJLfmWF6wUy9RnkF3ZiqP5YH8eXMnJIfmDIJbjEY3aMxaHOddSVTur7XeJVOIhaa6ynREXLTcbjlOh7PczULJxqcLAQ4sRnSx1pfYAf5N0oNwORPvxRCgl1sCxgeZWlwMaqPRhCZJsB1H15NHn95uvkMBMvD+0ABB629IJMK4yDKwhjGUjWKSZnjIfNZJJ2Q0nGbbEvQe+qJIYzVo0y5kE09BQ3j4nXbg/BvTzj+xTUkQyHkzsm2n2zqJA4WkWi3Z9wqsc71tn6RIFgaPTu3OG4RJkzmnlQCeFv00OWJUmH6ngEQ+FxSWNI7m6HhTQWrkDs+XyqS0At4ANXlIS2UkH2YFt6zWaw4VMNGTb2GY7DnAhg4Knf0ug+iaP4pIumoQD9qiODi4s/E4jQo9/g5P7PBvnF0fLztlO4pZjenZSk1BxO6aQwgVdAtnOLLYM+r+SawW8TN9fVN2WeYDvo8VrQ5DBqyiEx/G2JSzu3CgYC1yzsMDBNLVk6fatUVQFfr8tBi3HFslJ7uIrP/SYvqxXo7FczkoiR/F+cGEmVaPb3BgC9jwfOfiVGaOh8dQxkD86wq9nlJdyu+6WaJMRxZ4O0iQyVqbJVfJnzQP3BDl/jIc+WPq2LJM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
